preprocess:
  date_format: "%d/%m/%Y %H:%M"

split:
  test_size: 0.2
  random_state: 42
  target: "Load_Type"

train:
  model_type: "RandomForestClassifier"
  n_estimators: 200
  max_depth: 20
  min_samples_split: 2
  min_samples_leaf: 1
  max_features: "sqrt"
  random_state: 42